version: '2.3'

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      args:
        - UID=${USERID}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/usr/src
      - /mnt/D/Data/animefacedataset/images:/usr/src/data
    working_dir: /usr/src
    tty: true
    shm_size: '8gb'
